[project]
name = "cci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zaid Zada", email = "60576490+zaidzada@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cottoncandy>=0.4.0",
]

[project.scripts]
cci = "cci.cli:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
